---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: 12.19.36

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.0.118

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[hubrick-devops-challenge::default]
    attributes:
