---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: '13.0.118'

transport:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

provisioner:
  name: dokken

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install openssl apt-transport-https lsb-release procps net-tools iproute2 curl -y
