name             'hubrick-devops-challenge'
maintainer       'Ingo Dyck'
maintainer_email 'id@hubrick.com'
license          'All rights reserved'
description      'Installs/Configures hubrick-devops-challenge'
long_description 'Installs/Configures hubrick-devops-challenge'
issues_url       'https://github.com/bogus-py/hubrick-devops-challenge'
source_url       'https://github.com/bogus-py/hubrick-devops-challenge'
chef_version     '13.0.118'
supports         'ubuntu'
version          '0.1.0'
