name             'hubrick-devops-challenge'
maintainer       'Ingo Dyck'
maintainer_email 'id@hubrick.com'
license          'All rights reserved'
description      'Installs/Configures hubrick-devops-challenge'
long_description 'Installs/Configures hubrick-devops-challenge'
version          '0.1.0'
